spring:
  config:
    activate:
      on-profile: server
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/tune
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  output:
    ansi:
      enabled: always
server:
  port: 5000

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0

external:
  jwt:
    secret: ${JWT_SECRET}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    bundle-id: ${APPLE_BUNDLE_ID}
    private-key: ${APPLE_PRIVATE_KEY}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}

