spring:
  config:
    activate:
      on-profile: server
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
server:
  port: 5000

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0

external:
  jwt:
    secret: ${JWT_SECRET}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    bundle-id: ${APPLE_BUNDLE_ID}
    private-key: ${APPLE_PRIVATE_KEY}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}

